services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/codecake/postgresql/:/var/lib/postgresql/data

    environment:
      - 'POSTGRES_DB=airbnb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=root'
    ports:
      - 127.0.0.1:5432:5432
